import React, { createContext, useCallback, useContext, useEffect, useMemo, useState, ReactNode } from 'react';

export type Language = 'en' | 'hi' | 'ta' | 'mr' | 'kn';

type TranslationParams = Record<string, string | number>;
type Translations = Record<string, string>;

const STORAGE_KEY = 'civicsetu.language';

export const LANGUAGE_OPTIONS: { code: Language; label: string }[] = [
  { code: 'en', label: 'EN' },
  { code: 'hi', label: 'हि' },
  { code: 'ta', label: 'த' },
  { code: 'mr', label: 'म' },
  { code: 'kn', label: 'ಕ' },
];

export const LANGUAGE_SPEECH_LOCALES: Record<Language, string> = {
  en: 'en-IN',
  hi: 'hi-IN',
  ta: 'ta-IN',
  mr: 'mr-IN',
  kn: 'kn-IN',
};

export const LANGUAGE_ACCEPT_LOCALES: Record<Language, string> = {
  en: 'en,en-IN',
  hi: 'hi,en',
  ta: 'ta,en',
  mr: 'mr,en',
  kn: 'kn,en',
};

const baseTranslations: Translations = {
  'app.name': 'CIVICSETU',
  'app.tagline': 'Empowering citizens. Building better India.',
  'nav.back': 'Back to Home',
  'nav.logout': 'Logout',

  'common.cancel': 'Cancel',
  'common.close': 'Close',
  'common.profile': 'Profile',
  'common.details': 'Details',
  'common.changePhoto': 'Change Photo',
  'common.selectDefault': 'Select Default Avatar',
  'common.uploadCustom': 'Upload Custom Photo',
  'common.location': 'Location',
  'common.address': 'Address',
  'common.status': 'Status',
  'common.category': 'Category',
  'common.reportedOn': 'Reported On',
  'common.votes': 'Votes',
  'common.comments': 'Comments',
  'common.noComments': 'No comments yet.',
  'common.allStatuses': 'All Statuses',
  'common.allCategories': 'All Categories',
  'common.allStates': 'All States',
  'common.unresolved': 'Unresolved',
  'common.total': 'Total',
  'common.active': 'Active',
  'common.online': 'Online',
  'common.review': 'Review',
  'common.view': 'View',
  'common.pending': 'Pending',
  'common.approved': 'Approved',
  'common.rejected': 'Rejected',
  'button.approve': 'Approve',
  'button.reject': 'Reject',
  'status.approved': 'Approved',
  'status.rejected': 'Rejected',
  'common.up': 'Up',
  'common.down': 'Down',
  'common.live': 'Live',
  'common.issueCount': '{count} issues',
  'common.projectCount': '{count} projects',
  'common.requestCount': '{count} requests',
  'common.donorCount': '{count} donors',
  'common.contributionCount': '{count} contributions',
  'select.state': 'Select State',
  'select.category': 'Select Category',

  'status.open_for_bidding': 'Open for Bidding',
  'status.in_progress': 'In Progress',
  'status.awaiting_citizen_verification': 'Awaiting Citizen Verification',
  'status.resolved': 'Resolved',

  'urgency.high': 'High',
  'urgency.medium': 'Medium',
  'urgency.low': 'Low',

  'category.road': 'Road',
  'category.water': 'Water',
  'category.electricity': 'Electricity',
  'category.sanitation': 'Sanitation',

  'duplicate.raisedCount': 'Raised {count}x',

  'assigned.contractor': 'Assigned Contractor',
  'assigned.ngo': 'Assigned NGO',

  'beforeAfter.title': 'Before & After Comparison',
  'beforeAfter.before': 'Before - Citizen Reported',
  'beforeAfter.afterResolved': 'After - Issue Resolved',
  'beforeAfter.afterAwaiting': 'Proof Uploaded - Awaiting Citizen Verification',
  'beforeAfter.pending': 'Resolution Pending',
  'beforeAfter.pendingHelp': 'Resolution proof will appear here after the authority uploads it.',
  'beforeAfter.issueDetails': 'Issue Details',
  'beforeAfter.timesRaised': 'Times Raised',

  'donation.verifiedNgo': 'Verified NGO',
  'donation.totalReceived': 'Total Donations Received',
  'donation.selectAmount': 'Select Donation Amount',
  'donation.customAmount': 'Custom Amount (Rs)',
  'donation.customAmountPlaceholder': 'Enter custom amount',
  'donation.messageOptional': 'Message (Optional)',
  'donation.messagePlaceholder': 'Add a message of support...',
  'donation.demoInfo': 'This is a demo donation system. No real payment will be processed.',
  'donation.donateNow': 'Donate Now',
  'donation.thankYou': 'Thank You!',
  'donation.recordedAmount': 'Your donation of Rs {amount} has been recorded.',
  'donation.minAmountError': 'Minimum donation amount is Rs 100',
  'donation.footer': 'Together, we are building a better India.',

  'progress.title': 'Detailed Work Progress',
  'progress.reported': 'Issue Reported',
  'progress.verified': 'Authority Verified',
  'progress.budget': 'Funding Allocated',
  'progress.tendering': 'Tendering Process',
  'progress.assigned': 'Contractor Assigned',
  'progress.survey': 'Site Survey Done ("Sightseeing")',
  'progress.excavation': 'Excavation Started ("Dug up")',
  'progress.execution': 'Main Work Execution',
  'progress.audit': 'Quality Audit',
  'progress.resolved': 'Resolved',

  'landing.hero.badge': 'Active Across Multiple Indian States',
  'landing.login.citizen': 'Citizen Login',
  'landing.login.authority': 'Authority Login',
  'landing.login.contractor': 'Contractor Login',
  'landing.login.ngo': 'NGO Login',
  'landing.login.enter': 'Enter Portal',
  'landing.desc.citizen': 'Report civic issues, track progress, and stay connected with your community.',
  'landing.desc.authority': 'Manage civic issues, review contractors, and monitor resolution quality.',
  'landing.desc.contractor': 'Bid on civic projects, upload proof, and manage active assignments.',
  'landing.desc.ngo': 'Raise support requests, follow unresolved cases, and track community donations.',
  'landing.donate': 'Donate to NGO',
  'landing.stats.resolved': 'Issues Resolved',
  'landing.stats.states': 'States Covered',
  'landing.stats.ngos': 'Active NGOs',
  'landing.stats.contractors': 'Contractors',
  'landing.footer': '© 2026 CIVICSETU | Built for better civic engagement | All rights reserved.',
  'landing.modal.demo': 'CIVICSETU Platform - Demo Login',
  'landing.modal.fullName': 'Full Name',
  'landing.modal.email': 'Email',
  'landing.modal.password': 'Password',
  'landing.modal.namePlaceholder': 'Enter your name',
  'landing.modal.emailPlaceholder': 'Enter your email',
  'landing.modal.passwordPlaceholder': 'Password',
  'landing.modal.demoInfo': 'Demo credentials are pre-filled. Click login to continue.',
  'landing.modal.login': 'Login & Enter Portal',

  'citizen.title': 'Citizen Portal',
  'citizen.tab.issues': 'My Issues',
  'citizen.tab.report': 'Report Issue',
  'citizen.tab.chat': 'Chat',
  'citizen.tab.profile': 'Profile',
  'citizen.report.title': 'Report a New Issue',
  'citizen.report.issueTitle': 'Issue Title',
  'citizen.report.category': 'Category',
  'citizen.report.description': 'Description',
  'citizen.report.address': 'Street / Landmark',
  'citizen.report.state': 'State',
  'citizen.report.city': 'City',
  'citizen.report.landmark': 'Street / Landmark',
  'citizen.report.image': 'Upload Image',
  'citizen.report.voiceMode': 'Voice Mode',
  'citizen.report.typeMode': 'Type Mode',
  'citizen.report.submit': 'Submit Issue',
  'citizen.report.voiceHelp': 'Voice complaint mode helps citizens who are not comfortable typing.',
  'citizen.report.startRecord': 'Start Recording',
  'citizen.report.stopRecord': 'Stop Recording',
  'citizen.report.voiceConverted': 'Voice converted successfully!',
  'citizen.report.voiceFailed': 'Voice not clear. Please try again.',
  'citizen.report.recording': 'Recording...',
  'citizen.report.processing': 'Processing voice...',
  'citizen.report.autoLocation': 'Auto Location',
  'citizen.report.autoLocationHelp': 'Use your current location to preview the issue spot on the map and prefill nearby address details.',
  'citizen.report.useCurrentLocation': 'Use Current Location',
  'citizen.report.refreshLocation': 'Refresh Location',
  'citizen.report.detectingLocation': 'Detecting location...',
  'citizen.report.mapPlaceholder': 'Allow location access to preview your issue on OpenStreetMap.',
  'citizen.report.mapAccuracy': 'Approx. accuracy: {meters} m',
  'citizen.report.mapReady': 'OpenStreetMap preview ready',
  'citizen.report.mapFooter': 'Map tiles by OpenStreetMap. You can still edit the state, city, and landmark fields manually.',
  'citizen.report.descriptionPlaceholder': 'Describe the issue in detail...',
  'citizen.report.voiceAutofill': 'Auto-filled from voice input. You can edit this text.',
  'citizen.report.imageHelp': 'Upload a clear photo of the issue',
  'citizen.report.changeImage': 'Change Image',
  'citizen.report.chooseImage': 'Choose Image',
  'citizen.report.sampleImage': 'Use Sample Image',
  'citizen.report.imageUploaded': 'Image uploaded: {name}',

  'citizen.location.noBrowser': 'Location services are not available in this browser. Please enter the address manually.',
  'citizen.location.detectingAuto': 'Trying to detect your current location...',
  'citizen.location.detectingManual': 'Detecting your current location...',
  'citizen.location.captured': 'Current location captured. Updating nearby address details...',
  'citizen.location.updated': 'Current location captured and the address fields were updated. You can still edit them.',
  'citizen.location.lookupFallback': 'Current location captured. Address lookup is unavailable, so you can complete the text fields manually.',
  'citizen.location.genericError': 'Unable to detect your current location. Please enter the address manually.',
  'citizen.location.permissionDenied': 'Location access was blocked. Please allow location access and try again.',
  'citizen.location.timeout': 'Location detection timed out. Please try again in an open area or with a stronger signal.',

  'citizen.alert.requiredFields': 'Please fill all required fields.',
  'citizen.alert.verified': 'Issue verified and marked as resolved.',
  'citizen.alert.needsWork': 'Issue sent back to in-progress for more work.',
  'citizen.alert.duplicateMerged': 'Same issue already exists at this location. Raised count updated to {count}x.',
  'citizen.alert.submitted': 'Issue submitted successfully! It will appear in the dashboard shortly.',

  'citizen.issues.noIssues': 'No issues found.',
  'citizen.issues.viewDetails': 'View Details',
  'citizen.issues.filterCategory': 'Filter by Category',
  'citizen.issues.summaryFrozen': 'Community rating frozen at {score}/5 after a sudden batch of {count} reviews. Authority review is pending.',
  'citizen.suspicious': 'Flagged as suspicious',

  'citizen.chat.support': 'CIVICSETU Support',
  'citizen.chat.placeholder': 'Type your message...',
  'citizen.chat.send': 'Send',

  'citizen.profile.title': 'My Profile',
  'citizen.profile.trustCode': 'Trust Code',
  'citizen.profile.issues': 'Issues Raised',
  'citizen.profile.location': 'Location',
  'citizen.profile.role': 'Role',
  'citizen.profile.verifiedCitizen': 'Verified Citizen',
  'citizen.summary.title': 'Issue Summary',
  'citizen.summary.total': 'Total',
  'citizen.summary.resolved': 'Resolved',
  'citizen.summary.active': 'Active',

  'citizen.details.resolutionProof': 'Resolution Proof',
  'budget.label': 'Allocated Budget',
  'budget.transparency.title': 'Financial Transparency',
  'budget.allocation': 'Government Allocation',
  'budget.accepted': 'Accepted Bid',
  'budget.timeline': 'Estimated Timeline',
  'budget.days': '{{count}} Days',
  'issue.details.title': 'Issue Details',
  'citizen.details.reviewBeforeAfter': 'Review Before & After',
  'citizen.details.communityRating': 'Community Rating',
  'citizen.details.frozen': '(Frozen)',
  'citizen.details.freezeInfo': 'Rating freeze active: this issue received {count} quick reviews against a normal pace of about {expected} reviews/day.',
  'citizen.details.freezeTrustedScore': 'The trusted score is frozen at {score}/5 until authority completes manual review.',
  'citizen.details.authorityProofNotice': 'Authority has submitted proof. Only the reporting citizen can close this issue.',
  'citizen.details.verifyClose': 'Verify And Close Issue',
  'citizen.details.notSolvedYet': 'Not Solved Yet',
  'citizen.rate.label': 'Rate your experience',
  'citizen.donate': 'Donate to NGO',

  'authority.title': 'Authority Portal',
  'authority.subtitle': 'Municipal Corporation',
  'authority.tab.dashboard': 'Dashboard',
  'authority.tab.issues': 'All Issues',
  'authority.tab.bidding': 'Contractor Bids',
  'authority.tab.ngo': 'NGO Requests',
  'authority.dashboard.title': 'Dashboard Overview',
  'authority.dashboard.desc': 'Real-time civic issue management',
  'authority.kpi.resolved': 'Resolved',
  'authority.kpi.inProgress': 'In Progress',
  'authority.kpi.awaiting': 'Awaiting Citizen Verification',
  'authority.kpi.openBidding': 'Open for Bidding',
  'authority.kpi.highUrgency': 'High Urgency',
  'authority.kpi.suspicious': 'Suspicious',
  'authority.kpi.total': 'Total Issues',
  'authority.alert.suspicious': 'Suspicious Issues Alert ({count})',
  'authority.rankings.title': 'State Quality Rankings',
  'authority.rankings.desc': 'Historical score based on resolution rate, citizen ratings, trust signals, and pending verification load.',
  'authority.rankings.best': 'Best performer: {state} ({score}/100)',
  'authority.highPriority.title': 'High Priority Issues',
  'authority.table.image': 'Image',
  'authority.table.issue': 'Issue',
  'authority.table.category': 'Category',
  'authority.table.location': 'Location',
  'authority.table.status': 'Status',
  'authority.table.urgency': 'Urgency',
  'authority.table.action': 'Action',
  'authority.table.votes': 'Votes',
  'authority.bidding.info': 'Bidding is only enabled for issues with status "Open for Bidding". Once a bid is selected, status changes to "In Progress".',
  'authority.bidding.noBids': 'No bids received yet. Contractors will bid soon.',
  'authority.bidding.bidsReceived': '{count} Bid(s) Received',
  'authority.bidding.selectBid': 'Select Bid',
  'authority.ngo.noRequests': 'No NGO requests yet.',
  'authority.ngo.pending': 'Pending Approval',
  'authority.proof.required': 'Authority proof image is required before an issue can move for citizen verification.',
  'authority.proof.notice': 'Resolution proof has been submitted. This issue will stay open until the reporting citizen verifies that the work is complete.',
  'authority.profile.title': 'Authority Profile',
  'authority.profile.role': 'Role: Municipal Authority Officer',

  'contractor.title': 'Contractor Portal',
  'contractor.tab.bids': 'Open Bids',
  'contractor.tab.projects': 'My Projects',
  'contractor.tab.profile': 'Profile',
  'contractor.bids.kpi.opportunities': 'Open Opportunities',
  'contractor.bids.kpi.active': 'My Active Bids',
  'contractor.bids.kpi.selected': 'Bids Selected',
  'contractor.bids.info': 'You can only bid on issues with "Open for Bidding" status. Bidding is disabled once in progress or resolved.',
  'contractor.bids.submit': 'Submit Bid',
  'contractor.bids.noOpportunities': 'No open bidding issues available.',
  'contractor.bids.success': 'Bid submitted successfully! Authority will review and respond shortly.',
  'contractor.projects.earnings': 'Total Earnings',
  'contractor.projects.completion': 'Project Completion',
  'contractor.projects.left': 'Project Left',
  'contractor.projects.completed': 'Project Completed',
  'contractor.projects.pending': 'Project Pending',
  'contractor.projects.noProjects': 'No projects assigned yet. Submit bids on open issues!',
  'contractor.projects.contractValue': 'Contract Value: Rs {amount}',
  'contractor.projects.uploadProof': 'Upload After-Resolution Image',
  'contractor.projects.uploadPlaceholder': 'Image URL or leave blank to use default',
  'contractor.projects.uploadHelp': 'Leave URL blank to use a default resolution image for your category.',
  'contractor.projects.uploadSuccess': 'After-resolution image uploaded successfully!',
  'contractor.projects.verifyNotice': 'Authority has submitted proof. This project stays open until the reporting citizen verifies the fix.',
  'contractor.projects.rating': 'Citizen Rating: {stars} ({rating}/5)',
  'contractor.projects.viewNgo': 'View NGO & Support',
  'contractor.projects.viewBeforeAfter': 'View Before & After Comparison',
  'contractor.profile.title': 'Contractor Profile',
  'contractor.profile.company': 'Company',
  'contractor.profile.regId': 'Registration ID',
  'contractor.profile.rating': 'Platform Rating',
  'contractor.bidModal.title': 'Submit Your Bid',
  'contractor.bidModal.amount': 'Bid Amount (Rs) *',
  'contractor.bidModal.note': 'Proposal Note *',
  'contractor.bidModal.notePlaceholder': 'Describe your approach, timeline, materials...',

  'ngo.title': 'NGO Portal',
  'ngo.tab.issues': 'Unresolved Issues',
  'ngo.tab.requests': 'My Requests',
  'ngo.tab.analytics': 'Analytics',
  'ngo.tab.donations': 'Donations',
  'ngo.issues.noIssues': 'No unresolved issues found.',
  'ngo.requests.kpi.total': 'Total Requests',
  'ngo.requests.kpi.approved': 'Approved',
  'ngo.requests.kpi.pending': 'Pending',
  'ngo.requests.noRequests': 'No requests raised yet. Browse unresolved issues to raise requests.',
  'ngo.analytics.kpi.total': 'Total Issues',
  'ngo.analytics.kpi.unresolved': 'Unresolved',
  'ngo.analytics.kpi.resolved': 'Resolved',
  'ngo.analytics.kpi.participation': 'NGO Participation',
  'ngo.analytics.catTitle': 'Category Distribution',
  'ngo.analytics.urgencyTitle': 'Urgency Distribution (Active)',
  'ngo.analytics.stateTitle': 'State-wise Issue Analytics',
  'ngo.analytics.stateTop': 'Top state: {state} ({score}/100)',
  'ngo.analytics.participationTitle': 'NGO Participation Stats',
  'ngo.donations.totalReceived': 'Total Donations Received',
  'ngo.donations.contributions': '{count} contributions',
  'ngo.donations.help': 'Citizens can donate via the home page',
  'ngo.donations.history': 'Donation History',
  'ngo.request.raise': 'Raise Request',
  'ngo.request.alreadyRaised': 'You have already raised a request for this issue.',
  'ngo.request.success': 'Request raised successfully! Authority will review and respond shortly.',
  'ngo.profile.title': 'NGO Profile',
  'ngo.profile.totalDonations': 'Total Donations: Rs {amount}',
  'ngo.donationModal.title': 'Demo Donation',
  'ngo.donationModal.desc': 'This is a demo — no real payment processed',
  'ngo.donationModal.success': 'Donation Successful!',
  'ngo.donationModal.thanks': 'Thank you for supporting {name}!',
  'ngo.donationModal.donorName': 'Donor Name',
  'ngo.donationModal.amount': 'Amount (Rs)',
  'ngo.donationModal.card': 'Card Number (Demo)',
  'ngo.donationModal.expiry': 'Expiry',
  'ngo.donationModal.cvv': 'CVV',
  'ngo.donationModal.message': 'Message (optional)',
  'ngo.donationModal.submit': 'Donate Rs {amount} (Demo)',
};

const hiTranslations: Partial<Translations> = {
  'app.name': 'सिविकसेतु',
  'app.tagline': 'नागरिकों को सशक्त बनाना, बेहतर भारत बनाना।',
  'nav.logout': 'लॉग आउट',
  'common.cancel': 'रद्द करें',
  'common.close': 'बंद करें',
  'common.location': 'स्थान',
  'common.address': 'पता',
  'common.changePhoto': 'फोटो बदलें',
  'common.selectDefault': 'डिफ़ॉल्ट अवतार चुनें',
  'common.uploadCustom': 'फोटो अपलोड करें',
  'common.status': 'स्थिति',
  'common.category': 'श्रेणी',
  'common.reportedOn': 'रिपोर्ट की तिथि',
  'common.votes': 'वोट',
  'common.comments': 'टिप्पणियां',
  'common.noComments': 'अभी कोई टिप्पणी नहीं है।',
  'common.allStatuses': 'सभी स्थितियां',
  'common.allCategories': 'सभी श्रेणियां',
  'common.allStates': 'सभी राज्य',
  'common.unresolved': 'अनसुलझा',
  'common.total': 'कुल',
  'common.active': 'सक्रिय',
  'common.online': 'ऑनलाइन',
  'common.issueCount': '{count} समस्याएं',
  'common.projectCount': '{count} प्रोजेक्ट',
  'common.requestCount': '{count} अनुरोध',
  'common.donorCount': '{count} दानदाता',
  'common.contributionCount': '{count} योगदान',
  'common.up': 'समर्थन',
  'common.down': 'विरोध',
  'common.live': 'लाइव',
  'select.state': 'राज्य चुनें',
  'select.category': 'श्रेणी चुनें',

  'status.open_for_bidding': 'बोली के लिए खुला',
  'status.in_progress': 'कार्य प्रगति पर',
  'status.awaiting_citizen_verification': 'नागरिक सत्यापन लंबित',
  'status.resolved': 'समाधान हो चुका है',
  'status.approved': 'स्वीकृत',
  'status.rejected': 'अस्वीकृत',
  'button.approve': 'स्वीकृत करें',
  'button.reject': 'अस्वीकृत करें',

  'urgency.high': 'उच्च',
  'urgency.medium': 'मध्यम',
  'urgency.low': 'कम',

  'category.road': 'सड़क',
  'category.water': 'पानी',
  'category.electricity': 'बिजली',
  'category.sanitation': 'स्वच्छता',
  'duplicate.raisedCount': '{count} बार रिपोर्ट',

  'assigned.contractor': 'नियुक्त ठेकेदार',
  'assigned.ngo': 'नियुक्त एनजीओ',

  'beforeAfter.title': 'पहले और बाद की तुलना',
  'beforeAfter.before': 'पहले - नागरिक द्वारा रिपोर्ट',
  'beforeAfter.afterResolved': 'बाद में - समस्या हल',
  'beforeAfter.afterAwaiting': 'प्रमाण अपलोड - नागरिक सत्यापन लंबित',
  'beforeAfter.pending': 'समाधान लंबित',
  'beforeAfter.pendingHelp': 'अधिकारियों द्वारा प्रमाण अपलोड होने के बाद यह यहां दिखाई देगा।',
  'budget.label': 'आवंटित बजट',
  'budget.transparency.title': 'वित्तीय पारदर्शिता',
  'budget.allocation': 'सरकारी आवंटन',
  'budget.accepted': 'स्वीकृत बोली',
  'budget.timeline': 'अनुमानित समयसीमा',
  'budget.days': '{{count}} दिन',
  'issue.details.title': 'समस्या का विवरण',
  'beforeAfter.timesRaised': 'कितनी बार उठाया गया',

  'donation.verifiedNgo': 'सत्यापित एनजीओ',
  'donation.totalReceived': 'कुल प्राप्त दान',
  'donation.selectAmount': 'दान राशि चुनें',
  'donation.customAmount': 'कस्टम राशि (रु)',
  'donation.customAmountPlaceholder': 'राशि दर्ज करें',
  'donation.messageOptional': 'संदेश (वैकल्पिक)',
  'donation.messagePlaceholder': 'समर्थन का संदेश लिखें...',
  'donation.demoInfo': 'यह एक डेमो दान प्रणाली है। कोई वास्तविक भुगतान नहीं होगा।',
  'donation.donateNow': 'अभी दान करें',
  'donation.thankYou': 'धन्यवाद!',
  'donation.recordedAmount': 'आपका रु {amount} का दान दर्ज कर लिया गया है।',
  'donation.minAmountError': 'न्यूनतम दान राशि रु 100 है',
  'donation.footer': 'साथ मिलकर, हम एक बेहतर भारत बना रहे हैं।',

  'progress.title': 'विस्तृत कार्य प्रगति',
  'progress.reported': 'रिपोर्ट किया गया',
  'progress.verified': 'प्राधिकरण द्वारा सत्यापित',
  'progress.budget': 'बजट स्वीकृत',
  'progress.tendering': 'निविदा प्रक्रिया',
  'progress.assigned': 'ठेकेदार नियुक्त',
  'progress.survey': 'साइट सर्वे संपन्न ("साइट-विजिट")',
  'progress.excavation': 'खुदाई शुरू ("खोदना")',
  'progress.execution': 'मुख्य कार्य निष्पादन',
  'progress.audit': 'गुणवत्ता जांच',
  'progress.resolved': 'समाधान हल',

  'landing.hero.badge': 'कई भारतीय राज्यों में सक्रिय',
  'landing.login.citizen': 'नागरिक लॉगिन',
  'landing.login.authority': 'प्राधिकरण लॉगिन',
  'landing.login.contractor': 'ठेकेदार लॉगिन',
  'landing.login.ngo': 'एनजीओ लॉगिन',
  'landing.login.enter': 'पोर्टल में प्रवेश करें',
  'landing.desc.citizen': 'नागरिक समस्याएं दर्ज करें, प्रगति ट्रैक करें और समुदाय से जुड़ें।',
  'landing.desc.authority': 'समस्याएं संभालें, ठेकेदारों की समीक्षा करें और समाधान की गुणवत्ता देखें।',
  'landing.desc.contractor': 'सिविक प्रोजेक्ट पर बोली लगाएं, प्रमाण अपलोड करें और अपने कार्य संभालें।',
  'landing.desc.ngo': 'सहायता अनुरोध उठाएं, लंबित मामलों को फॉलो करें और दान ट्रैक करें।',
  'landing.donate': 'एनजीओ को दान दें',
  'landing.stats.resolved': 'हल की गई समस्याएं',
  'landing.stats.states': 'कवर किए गए राज्य',
  'landing.stats.ngos': 'सक्रिय एनजीओ',
  'landing.stats.contractors': 'ठेकेदार',
  'landing.footer': '© 2026 CIVICSETU | बेहतर नागरिक भागीदारी के लिए बनाया गया | सर्वाधिकार सुरक्षित।',
  'landing.modal.demo': 'CIVICSETU प्लेटफॉर्म - डेमो लॉगिन',
  'landing.modal.fullName': 'पूरा नाम',
  'landing.modal.email': 'ईमेल',
  'landing.modal.password': 'पासवर्ड',
  'landing.modal.namePlaceholder': 'अपना नाम दर्ज करें',
  'landing.modal.emailPlaceholder': 'अपना ईमेल दर्ज करें',
  'landing.modal.passwordPlaceholder': 'पासवर्ड',
  'landing.modal.demoInfo': 'डेमो क्रेडेंशियल पहले से भरे हुए हैं। आगे बढ़ने के लिए लॉगिन करें।',
  'landing.modal.login': 'लॉगिन करें और पोर्टल खोलें',

  'citizen.title': 'नागरिक पोर्टल',
  'citizen.tab.issues': 'मेरी समस्याएं',
  'citizen.tab.report': 'समस्या दर्ज करें',
  'citizen.tab.chat': 'चैट',
  'citizen.tab.profile': 'प्रोफाइल',
  'citizen.report.title': 'नई समस्या दर्ज करें',
  'citizen.report.issueTitle': 'समस्या का शीर्षक',
  'citizen.report.category': 'श्रेणी',
  'citizen.report.description': 'विवरण',
  'citizen.report.address': 'गली / लैंडमार्क',
  'citizen.report.state': 'राज्य',
  'citizen.report.city': 'शहर',
  'citizen.report.landmark': 'गली / लैंडमार्क',
  'citizen.report.image': 'छवि अपलोड करें',
  'citizen.report.voiceMode': 'आवाज मोड',
  'citizen.report.typeMode': 'टाइप मोड',
  'citizen.report.submit': 'समस्या जमा करें',
  'citizen.report.voiceHelp': 'आवाज मोड उन नागरिकों की मदद करता है जिन्हें टाइप करना आसान नहीं लगता।',
  'citizen.report.startRecord': 'रिकॉर्डिंग शुरू करें',
  'citizen.report.stopRecord': 'रिकॉर्डिंग बंद करें',
  'citizen.report.voiceConverted': 'आवाज सफलतापूर्वक बदली गई!',
  'citizen.report.voiceFailed': 'आवाज साफ नहीं थी। कृपया फिर से कोशिश करें।',
  'citizen.report.recording': 'रिकॉर्डिंग...',
  'citizen.report.processing': 'आवाज प्रोसेस हो रही है...',
  'citizen.report.autoLocation': 'ऑटो लोकेशन',
  'citizen.report.autoLocationHelp': 'अपनी वर्तमान लोकेशन से मैप प्रीव्यू देखें और पास का पता अपने आप भरें।',
  'citizen.report.useCurrentLocation': 'वर्तमान लोकेशन लें',
  'citizen.report.refreshLocation': 'लोकेशन रीफ्रेश करें',
  'citizen.report.detectingLocation': 'लोकेशन ढूंढी जा रही है...',
  'citizen.report.mapPlaceholder': 'OpenStreetMap पर प्रीव्यू देखने के लिए लोकेशन एक्सेस दें।',
  'citizen.report.mapAccuracy': 'लगभग सटीकता: {meters} मी',
  'citizen.report.mapReady': 'OpenStreetMap प्रीव्यू तैयार है',
  'citizen.report.mapFooter': 'मैप टाइल्स OpenStreetMap द्वारा हैं। आप राज्य, शहर और लैंडमार्क को हाथ से बदल सकते हैं।',
  'citizen.report.descriptionPlaceholder': 'समस्या का पूरा विवरण लिखें...',
  'citizen.report.voiceAutofill': 'आवाज इनपुट से टेक्स्ट भरा गया है। आप इसे बदल सकते हैं।',
  'citizen.report.imageHelp': 'समस्या की साफ फोटो अपलोड करें',
  'citizen.report.changeImage': 'छवि बदलें',
  'citizen.report.chooseImage': 'छवि चुनें',
  'citizen.report.sampleImage': 'नमूना छवि लें',
  'citizen.report.imageUploaded': 'छवि अपलोड हो गई: {name}',

  'citizen.location.noBrowser': 'इस ब्राउज़र में लोकेशन सेवा उपलब्ध नहीं है। कृपया पता मैन्युअली भरें।',
  'citizen.location.detectingAuto': 'आपकी वर्तमान लोकेशन ढूंढने की कोशिश की जा रही है...',
  'citizen.location.detectingManual': 'आपकी वर्तमान लोकेशन ढूंढी जा रही है...',
  'citizen.location.captured': 'लोकेशन मिल गई। पास के पते की जानकारी अपडेट की जा रही है...',
  'citizen.location.updated': 'लोकेशन मिल गई और पता वाले फ़ील्ड अपडेट हो गए। आप इन्हें बदल सकते हैं।',
  'citizen.location.lookupFallback': 'लोकेशन मिल गई। पता खोज उपलब्ध नहीं है, इसलिए आप बाकी फ़ील्ड हाथ से भर सकते हैं।',
  'citizen.location.genericError': 'आपकी वर्तमान लोकेशन नहीं मिल सकी। कृपया पता मैन्युअली भरें।',
  'citizen.location.permissionDenied': 'लोकेशन एक्सेस रोक दी गई है। कृपया अनुमति दें और फिर कोशिश करें।',
  'citizen.location.timeout': 'लोकेशन ढूंढने में समय लग गया। कृपया खुले क्षेत्र में फिर से कोशिश करें।',

  'citizen.alert.requiredFields': 'कृपया सभी जरूरी फ़ील्ड भरें।',
  'citizen.alert.verified': 'समस्या सत्यापित हो गई और resolved चिह्नित कर दी गई।',
  'citizen.alert.needsWork': 'समस्या को और काम के लिए फिर से in-progress में भेज दिया गया।',
  'citizen.alert.duplicateMerged': 'यही समस्या इस स्थान पर पहले से मौजूद है। Raised count {count}x कर दिया गया है।',
  'citizen.alert.submitted': 'समस्या सफलतापूर्वक जमा हो गई! यह जल्द डैशबोर्ड में दिखेगी।',

  'citizen.issues.noIssues': 'कोई समस्या नहीं मिली।',
  'citizen.issues.viewDetails': 'विवरण देखें',
  'citizen.issues.summaryFrozen': 'कम समय में {count} रिव्यू आने पर कम्युनिटी रेटिंग {score}/5 पर फ्रीज़ कर दी गई है। अथॉरिटी समीक्षा लंबित है।',
  'citizen.suspicious': 'संदिग्ध के रूप में चिह्नित',

  'citizen.chat.support': 'CIVICSETU सहायता',
  'citizen.chat.placeholder': 'अपना संदेश लिखें...',
  'citizen.chat.send': 'भेजें',

  'citizen.profile.title': 'मेरी प्रोफाइल',
  'citizen.profile.trustCode': 'ट्रस्ट कोड',
  'citizen.profile.issues': 'उठाई गई समस्याएं',
  'citizen.profile.location': 'स्थान',
  'citizen.profile.role': 'भूमिका',
  'citizen.profile.verifiedCitizen': 'सत्यापित नागरिक',
  'citizen.summary.title': 'समस्या सारांश',
  'citizen.summary.total': 'कुल',
  'citizen.summary.resolved': 'हल',
  'citizen.summary.active': 'सक्रिय',

  'citizen.details.resolutionProof': 'समाधान प्रमाण',
  'citizen.details.allocatedBudget': 'आवंटित बजट',
  'citizen.details.reviewBeforeAfter': 'पहले और बाद की समीक्षा करें',
  'citizen.details.communityRating': 'कम्युनिटी रेटिंग',
  'citizen.details.frozen': '(फ्रीज़)',
  'citizen.details.freezeInfo': 'रेटिंग फ्रीज़ सक्रिय है: इस समस्या पर कम समय में {count} रिव्यू आए, जबकि सामान्य गति लगभग {expected} रिव्यू प्रति दिन है।',
  'citizen.details.freezeTrustedScore': 'भरोसेमंद स्कोर {score}/5 पर फ्रीज़ है, जब तक अथॉरिटी मैन्युअल समीक्षा पूरी नहीं करती।',
  'citizen.details.authorityProofNotice': 'अथॉरिटी ने प्रमाण जमा किया है। केवल रिपोर्ट करने वाला नागरिक ही इस समस्या को बंद कर सकता है।',
  'citizen.details.verifyClose': 'सत्यापित करें और समस्या बंद करें',
  'citizen.details.notSolvedYet': 'अभी हल नहीं हुई',
  'citizen.rate.label': 'अपने अनुभव को रेट करें',
  'citizen.donate': 'एनजीओ को दान दें',

  'authority.title': 'प्राधिकरण पोर्टल',
  'authority.subtitle': 'नगर निगम',
  'authority.tab.dashboard': 'डैशबोर्ड',
  'authority.tab.issues': 'सभी समस्याएं',
  'authority.tab.bidding': 'ठेकेदार बोलियां',
  'authority.tab.ngo': 'एनजीओ अनुरोध',
  'authority.dashboard.title': 'डैशबोर्ड अवलोकन',
  'authority.dashboard.desc': 'वास्तविक समय नागरिक समस्या प्रबंधन',
  'authority.kpi.resolved': 'हल हो चुके',
  'authority.kpi.inProgress': 'प्रगति पर',
  'authority.kpi.awaiting': 'नागरिक सत्यापन लंबित',
  'authority.kpi.openBidding': 'बोली के लिए खुला',
  'authority.kpi.highUrgency': 'उच्च प्राथमिकता',
  'authority.kpi.suspicious': 'संदिग्ध',
  'authority.kpi.total': 'कुल समस्याएं',
  'authority.alert.suspicious': 'संदिग्ध समस्या अलर्ट ({count})',
  'authority.rankings.title': 'राज्य गुणवत्ता रैंकिंग',
  'authority.rankings.desc': 'समाधान दर, नागरिक रेटिंग, और सत्यापन भार के आधार पर ऐतिहासिक स्कोर।',
  'authority.rankings.best': 'सर्वश्रेष्ठ प्रदर्शन: {state} ({score}/100)',
  'authority.highPriority.title': 'उच्च प्राथमिकता वाली समस्याएं',
  'authority.table.image': 'छवि',
  'authority.table.issue': 'समस्या',
  'authority.table.category': 'श्रेणी',
  'authority.table.location': 'स्थान',
  'authority.table.status': 'स्थिति',
  'authority.table.urgency': 'प्राथमिकता',
  'authority.table.action': 'कार्य',
  'authority.table.votes': 'वोट',
  'authority.bidding.info': 'बोली केवल "Open for Bidding" स्थिति वाली समस्याओं के लिए सक्षम है। बोली चुनने के बाद स्थिति "In Progress" हो जाती है।',
  'authority.bidding.noBids': 'अभी तक कोई बोली प्राप्त नहीं हुई है। ठेकेदार जल्द ही बोली लगाएंगे।',
  'authority.bidding.bidsReceived': '{count} बोलियां प्राप्त हुईं',
  'authority.bidding.selectBid': 'बोली चुनें',
  'authority.ngo.noRequests': 'अभी तक कोई एनजीओ अनुरोध नहीं है।',
  'authority.ngo.pending': 'अनुमोदन लंबित',
  'authority.proof.required': 'समस्या को नागरिक सत्यापन के लिए भेजने से पहले प्राधिकरण प्रमाण छवि आवश्यक है।',
  'authority.proof.notice': 'समाधान का प्रमाण जमा कर दिया गया है। यह समस्या तब तक खुली रहेगी जब तक रिपोर्ट करने वाला नागरिक इसकी पुष्टि नहीं कर देता।',
  'authority.profile.title': 'प्राधिकरण प्रोफाइल',
  'authority.profile.role': 'भूमिका: नगर निगम अधिकारी',

  'contractor.title': 'ठेकेदार पोर्टल',
  'contractor.tab.bids': 'खुली बोलियां',
  'contractor.tab.projects': 'मेरे प्रोजेक्ट',
  'contractor.tab.profile': 'प्रोफाइल',
  'contractor.bids.kpi.opportunities': 'खुले अवसर',
  'contractor.bids.kpi.active': 'मेरी सक्रिय बोलियां',
  'contractor.bids.kpi.selected': 'चुनी गई बोलियां',
  'contractor.bids.info': 'आप केवल "Open for Bidding" स्थिति वाली समस्याओं पर बोली लगा सकते हैं। प्रगति पर या हल होने के बाद बोली अक्षम हो जाती है।',
  'contractor.bids.submit': 'बोली लगाएं',
  'contractor.bids.noOpportunities': 'कोई खुली बोली उपलब्ध नहीं है।',
  'contractor.bids.success': 'बोली सफलतापूर्वक जमा हो गई! प्राधिकरण समीक्षा करेगा और जल्द उत्तर देगा।',
  'contractor.projects.earnings': 'कुल कमाई',
  'contractor.projects.completion': 'परियोजना पूर्णता',
  'contractor.projects.left': 'परियोजना शेष',
  'contractor.projects.completed': 'परियोजना पूर्ण',
  'contractor.projects.pending': 'परियोजना लंबित',
  'contractor.projects.noProjects': 'अभी तक कोई प्रोजेक्ट आवंटित नहीं किया गया है। खुली समस्याओं पर बोली लगाएं!',
  'contractor.projects.contractValue': 'अनुबंध मूल्य: रु {amount}',
  'contractor.projects.uploadProof': 'समाधान के बाद की छवि अपलोड करें',
  'contractor.projects.uploadPlaceholder': 'छवि URL या डिफ़ॉल्ट के लिए खाली छोड़ें',
  'contractor.projects.uploadHelp': 'अपनी श्रेणी के लिए डिफ़ॉल्ट छवि का उपयोग करने के लिए URL खाली छोड़ें।',
  'contractor.projects.uploadSuccess': 'समाधान के बाद की छवि सफलतापूर्वक अपलोड की गई!',
  'contractor.projects.verifyNotice': 'प्राधिकरण ने प्रमाण जमा कर दिया है। रिपोर्ट करने वाले नागरिक द्वारा पुष्टि किए जाने तक यह प्रोजेक्ट खुला रहेगा।',
  'contractor.projects.rating': 'नागरिक रेटिंग: {stars} ({rating}/5)',
  'contractor.projects.viewNgo': 'एनजीओ देखें और सहायता करें',
  'contractor.projects.viewBeforeAfter': 'पहले और बाद की तुलना देखें',
  'contractor.profile.title': 'ठेकेदार प्रोफाइल',
  'contractor.profile.company': 'कंपनी',
  'contractor.profile.regId': 'पंजीकरण आईडी',
  'contractor.profile.rating': 'प्लेटफ़ॉर्म रेटिंग',
  'contractor.bidModal.title': 'अपनी बोली लगाएं',
  'contractor.bidModal.amount': 'बोली राशि (रु) *',
  'contractor.bidModal.note': 'प्रस्ताव नोट *',
  'contractor.bidModal.notePlaceholder': 'अपना दृष्टिकोण, समयरेखा, सामग्री आदि बताएं...',

  'ngo.title': 'एनजीओ पोर्टल',
  'ngo.tab.issues': 'अनसुलझी समस्याएं',
  'ngo.tab.requests': 'मेरे अनुरोध',
  'ngo.tab.analytics': 'एनालिटिक्स',
  'ngo.tab.donations': 'दान',
  'ngo.issues.noIssues': 'कोई अनसुलझी समस्या नहीं मिली।',
  'ngo.request.kpi.total': 'कुल अनुरोध',
  'ngo.request.pending': 'लंबित',
  'ngo.request.noRequests': 'अभी तक कोई अनुरोध नहीं किया गया है। अनुरोध करने के लिए अनसुलझी समस्याओं को देखें।',
  'ngo.analytics.participation': 'एनजीओ भागीदारी',
  'ngo.analytics.catDist': 'श्रेणी वितरण',
  'ngo.analytics.urgDist': 'प्राथमिकता वितरण (सक्रिय)',
  'ngo.analytics.stateAnalytics': 'राज्य-वार समस्या विश्लेषण',
  'ngo.analytics.stateDesc': 'समाधान दर, नागरिक रेटिंग, और सत्यापन भार के आधार पर ऐतिहासिक स्कोर।',
  'ngo.analytics.topState': 'शीर्ष राज्य',
  'ngo.analytics.quality': 'गुणवत्ता स्कोर',
  'ngo.analytics.resolvedCount': 'हल की गई समस्याएं',
  'ngo.analytics.resolvedShort': 'हल',
  'ngo.analytics.ratingShort': 'रेटिंग',
  'ngo.analytics.trustShort': 'ट्रस्ट',
  'ngo.analytics.reqRaised': 'अनुरोध उठाए गए',
  'ngo.donations.total': 'कुल प्राप्त दान',
  'ngo.donations.contributions': '{count} योगदान',
  'ngo.donations.tip': 'नागरिक होम पेज के माध्यम से दान कर सकते हैं',
  'ngo.donations.history': 'दान इतिहास',
  'ngo.donations.received': 'प्राप्त दान',
  'ngo.donationModal.title': 'डेमो दान',
  'ngo.donationModal.demo': 'यह एक डेमो है — कोई वास्तविक भुगतान नहीं होगा',
  'ngo.donationModal.success': 'दान सफल रहा!',
  'ngo.donationModal.successMsg': '{name} की सहायता करने के लिए धन्यवाद!',
  'ngo.donationModal.demoNotice': 'डेमो केवल - कोई वास्तविक भुगतान नहीं होगा',
  'ngo.donationModal.donor': 'दानदाता का नाम',
  'ngo.donationModal.donorPlaceholder': 'आपका नाम',
  'ngo.donationModal.amountLabel': 'राशि (रु)',
  'ngo.donationModal.customPlaceholder': 'कस्टम राशि दर्ज करें',
  'ngo.donationModal.card': 'कार्ड नंबर (डेमो)',
  'ngo.donationModal.expiry': 'समाप्ति',
  'ngo.donationModal.cvv': 'CVV',
  'ngo.donationModal.message': 'संदेश (वैकल्पिक)',
  'ngo.donationModal.messagePlaceholder': 'समर्थन का संदेश लिखें...',
  'ngo.donationModal.submit': 'रु {amount} दान करें (डेमो)',
  'ngo.profile.title': 'एनजीओ प्रोफाइल',
  'ngo.profile.rating': 'प्लेटफ़ॉर्म रेटिंग',
  'ngo.request.duplicate': 'आप पहले ही इस समस्या के लिए अनुरोध कर चुके हैं।',
  'ngo.request.success': 'अनुरोध सफलतापूर्वक उठाया गया! प्राधिकरण समीक्षा करेगा और जल्द उत्तर देगा।',
  'ngo.request.at': 'अनुरोध की तिथि',
  'ngo.analytics.issues': 'समस्याएं',
};

const taTranslations: Partial<Translations> = {
  'app.name': 'சிவிக்சேது',
  'app.tagline': 'குடிமக்களை சக்திவாய்ந்தவர்களாக மாற்றி, சிறந்த இந்தியாவை உருவாக்குவோம்.',
  'nav.logout': 'வெளியேறு',
  'common.cancel': 'ரத்து செய்',
  'common.close': 'மூடு',
  'common.location': 'இடம்',
  'common.up': 'ஆதரவு',
  'common.down': 'எதிர்ப்பு',
  'common.live': 'நேரடி',
  'common.status': 'நிலை',
  'common.category': 'வகை',
  'common.allStatuses': 'அனைத்து நிலைகளும்',
  'common.allCategories': 'அனைத்து வகைகளும்',
  'common.allStates': 'அனைத்து மாநிலங்களும்',
  'status.open_for_bidding': 'ஏலத்துக்கு திறந்தது',
  'status.in_progress': 'செயலில் உள்ளது',
  'status.awaiting_citizen_verification': 'குடிமக்கள் சரிபார்ப்பு நிலுவை',
  'status.resolved': 'தீர்க்கப்பட்டது',
  'category.road': 'சாலை',
  'category.water': 'தண்ணீர்',
  'category.electricity': 'மின்சாரம்',
  'category.sanitation': 'சுகாதாரம்',
  'duplicate.raisedCount': '{count} முறை எழுப்பப்பட்டது',
  'landing.hero.badge': 'பல இந்திய மாநிலங்களில் செயல்படுகிறது',
  'landing.login.citizen': 'குடிமக்கள் உள்நுழைவு',
  'landing.login.authority': 'அதிகாரி உள்நுழைவு',
  'landing.login.contractor': 'ஒப்பந்ததாரர் உள்நுழைவு',
  'landing.login.ngo': 'என்ஜிஓ உள்நுழைவு',
  'landing.login.enter': 'போர்ட்டலுக்கு செல்லவும்',
  'landing.donate': 'என்ஜிஓக்கு நன்கொடை அளிக்கவும்',
  'select.state': 'மாநிலத்தை தேர்ந்தெடுக்கவும்',
  'select.category': 'வகையை தேர்ந்தெடுக்கவும்',
  'landing.stats.resolved': 'தீர்க்கப்பட்ட பிரச்சினைகள்',
  'landing.stats.states': 'உள்ளடக்கப்பட்ட மாநிலங்கள்',
  'landing.stats.ngos': 'செயலில் உள்ள என்ஜிஓக்கள்',
  'landing.stats.contractors': 'ஒப்பந்ததாரர்கள்',
  'citizen.title': 'குடிமக்கள் போர்ட்டல்',
  'citizen.tab.issues': 'என் பிரச்சினைகள்',
  'citizen.tab.report': 'பிரச்சினை பதிவு',
  'citizen.tab.chat': 'அரட்டை',
  'citizen.tab.profile': 'சுயவிவரம்',
  'citizen.report.title': 'புதிய பிரச்சினையை பதிவு செய்யவும்',
  'citizen.report.category': 'வகை',
  'citizen.report.description': 'விவரம்',
  'citizen.report.state': 'மாநிலம்',
  'citizen.report.city': 'நகர்',
  'citizen.report.submit': 'பிரச்சினையை சமர்ப்பிக்கவும்',
  'citizen.chat.support': 'CIVICSETU உதவி',
  'citizen.chat.placeholder': 'உங்கள் செய்தியை টাইப் செய்யுங்கள்...',
  'citizen.profile.title': 'என் சுயவிவரம்',
  'citizen.summary.title': 'பிரச்சினை சுருக்கம்',
  'citizen.donate': 'என்ஜிஓக்கு நன்கொடை அளிக்கவும்',
  'authority.title': 'அதிகாரி போர்ட்டல்',
  'authority.tab.dashboard': 'டாஷ்போர்டு',
  'authority.tab.issues': 'அனைத்து பிரச்சினைகள்',
  'authority.tab.bidding': 'ஒப்பந்த ஏலங்கள்',
  'authority.tab.ngo': 'என்ஜிஓ கோரிக்கைகள்',
  'contractor.title': 'ஒப்பந்ததாரர் போர்ட்டல்',
  'contractor.tab.bids': 'திறந்த ஏலங்கள்',
  'contractor.tab.projects': 'என் திட்டங்கள்',
  'contractor.tab.profile': 'சுயவிவரம்',
  'ngo.title': 'என்ஜிஓ போர்ட்டல்',
  'ngo.tab.issues': 'தீர்க்காத பிரச்சினைகள்',
  'ngo.tab.requests': 'என் கோரிக்கைகள்',
  'ngo.tab.analytics': 'பகுப்பாய்வு',
  'ngo.tab.donations': 'நன்கொடைகள்',
};

const mrTranslations: Partial<Translations> = {
  'app.name': 'सिविकसेतु',
  'app.tagline': 'नागरिकांना सक्षम बनवून, चांगले भारत घडवूया.',
  'nav.logout': 'लॉग आउट',
  'common.cancel': 'रद्द करा',
  'common.close': 'बंद करा',
  'common.location': 'स्थान',
  'common.up': 'समर्थन',
  'common.down': 'विरोध',
  'common.live': 'लाईव्ह',
  'common.status': 'स्थिती',
  'common.category': 'श्रेणी',
  'common.allStatuses': 'सर्व स्थिती',
  'common.allCategories': 'सर्व श्रेण्या',
  'common.allStates': 'सर्व राज्ये',
  'status.open_for_bidding': 'बोलीसाठी खुले',
  'status.in_progress': 'काम सुरू आहे',
  'status.awaiting_citizen_verification': 'नागरिक पडताळणी प्रलंबित',
  'status.resolved': 'निकाली निघाले',
  'category.road': 'रस्ता',
  'category.water': 'पाणी',
  'category.electricity': 'वीज',
  'category.sanitation': 'स्वच्छता',
  'duplicate.raisedCount': '{count} वेळा नोंदवले',
  'landing.hero.badge': 'अनेक भारतीय राज्यांमध्ये सक्रिय',
  'landing.login.citizen': 'नागरिक लॉगिन',
  'landing.login.authority': 'प्राधिकरण लॉगिन',
  'landing.login.contractor': 'कंत्राटदार लॉगिन',
  'landing.login.ngo': 'एनजीओ लॉगिन',
  'landing.login.enter': 'पोर्टलमध्ये जा',
  'landing.donate': 'एनजीओला देणगी द्या',
  'select.state': 'राज्य निवडा',
  'select.category': 'श्रेणी निवडा',
  'landing.stats.resolved': 'निकाली काढलेले मुद्दे',
  'landing.stats.states': 'समाविष्ट राज्ये',
  'landing.stats.ngos': 'सक्रिय एनजीओ',
  'landing.stats.contractors': 'कंत्राटदार',
  'citizen.title': 'नागरिक पोर्टल',
  'citizen.tab.issues': 'माझे मुद्दे',
  'citizen.tab.report': 'मुद्दा नोंदवा',
  'citizen.tab.chat': 'चॅट',
  'citizen.tab.profile': 'प्रोफाइल',
  'citizen.report.title': 'नवीन समस्या नोंदवा',
  'citizen.report.category': 'श्रेणी',
  'citizen.report.description': 'वर्णन',
  'citizen.report.state': 'राज्य',
  'citizen.report.city': 'शहर',
  'citizen.report.submit': 'मुद्दा सबमिट करा',
  'citizen.chat.support': 'CIVICSETU सहाय्य',
  'citizen.chat.placeholder': 'तुमचा संदेश टाइप करा...',
  'citizen.profile.title': 'माझे प्रोफाइल',
  'citizen.summary.title': 'समस्या सारांश',
  'citizen.donate': 'एनजीओला देणगी द्या',
  'authority.title': 'प्राधिकरण पोर्टल',
  'authority.tab.dashboard': 'डॅशबोर्ड',
  'authority.tab.issues': 'सर्व मुद्दे',
  'authority.tab.bidding': 'कंत्राटदार बोली',
  'authority.tab.ngo': 'एनजीओ विनंत्या',
  'contractor.title': 'कंत्राटदार पोर्टल',
  'contractor.tab.bids': 'उघड्या बोली',
  'contractor.tab.projects': 'माझे प्रोजेक्ट',
  'contractor.tab.profile': 'प्रोफाइल',
  'ngo.title': 'एनजीओ पोर्टल',
  'ngo.tab.issues': 'अनिर्णित मुद्दे',
  'ngo.tab.requests': 'माझ्या विनंत्या',
  'ngo.tab.analytics': 'विश्लेषण',
  'ngo.tab.donations': 'देणग्या',
};

const knTranslations: Partial<Translations> = {
  'app.name': 'ಸಿವಿಕ್‌ಸೆತು',
  'app.tagline': 'ನಾಗರಿಕರನ್ನು ಶಕ್ತಿಶಾಲಿಗಳನ್ನಾಗಿ ಮಾಡಿ, ಉತ್ತಮ ಭಾರತವನ್ನು ನಿರ್ಮಿಸೋಣ.',
  'nav.logout': 'ಲಾಗ್ ಔಟ್',
  'common.cancel': 'ರದ್ದುಮಾಡಿ',
  'common.close': 'ಮುಚ್ಚಿ',
  'common.location': 'ಸ್ಥಳ',
  'common.up': 'ಬೆಂಬಲ',
  'common.down': 'ವಿರೋಧ',
  'common.live': 'ಲೈವ್',
  'common.status': 'ಸ್ಥಿತಿ',
  'common.category': 'ವರ್ಗ',
  'common.allStatuses': 'ಎಲ್ಲಾ ಸ್ಥಿತಿಗಳು',
  'common.allCategories': 'ಎಲ್ಲಾ ವರ್ಗಗಳು',
  'common.allStates': 'ಎಲ್ಲಾ ರಾಜ್ಯಗಳು',
  'status.open_for_bidding': 'ಬಿದ್ದಿಂಗ್‌ಗೆ ತೆರೆಯಲಾಗಿದೆ',
  'status.in_progress': 'ಪ್ರಗತಿಯಲ್ಲಿದೆ',
  'status.awaiting_citizen_verification': 'ನಾಗರಿಕ ಪರಿಶೀಲನೆ ಬಾಕಿ',
  'status.resolved': 'ಪರಿಹರಿಸಲಾಗಿದೆ',
  'category.road': 'ರಸ್ತೆ',
  'category.water': 'ನೀರು',
  'category.electricity': 'ವಿದ್ಯುತ್',
  'category.sanitation': 'ಸ್ವಚ್ಛತೆ',
  'duplicate.raisedCount': '{count} ಬಾರಿ ಎತ್ತಲಾಗಿದೆ',
  'landing.hero.badge': 'ಹಲವಾರು ಭಾರತೀಯ ರಾಜ್ಯಗಳಲ್ಲಿ ಸಕ್ರಿಯ',
  'landing.login.citizen': 'ನಾಗರಿಕ ಲಾಗಿನ್',
  'landing.login.authority': 'ಅಧಿಕಾರಿ ಲಾಗಿನ್',
  'landing.login.contractor': 'ಕಾಂಟ್ರಾಕ್ಟರ್ ಲಾಗಿನ್',
  'landing.login.ngo': 'ಎನ್‌ಜಿಒ ಲಾಗಿನ್',
  'landing.login.enter': 'ಪೋರ್ಟಲ್‌ಗೆ ಹೋಗಿ',
  'landing.donate': 'ಎನ್‌ಜಿಒಗೆ ದೇಣಿಗೆ ನೀಡಿ',
  'select.state': 'ರಾಜ್ಯವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
  'select.category': 'ವರ್ಗವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
  'landing.stats.resolved': 'ಪರಿಹರಿಸಿದ ಸಮಸ್ಯೆಗಳು',
  'landing.stats.states': 'ಆವರಿಸಿದ ರಾಜ್ಯಗಳು',
  'landing.stats.ngos': 'ಸಕ್ರಿಯ ಎನ್‌ಜಿಒಗಳು',
  'landing.stats.contractors': 'ಕಾಂಟ್ರಾಕ್ಟರ್‌ಗಳು',
  'citizen.title': 'ನಾಗರಿಕ ಪೋರ್ಟಲ್',
  'citizen.tab.issues': 'ನನ್ನ ಸಮಸ್ಯೆಗಳು',
  'citizen.tab.report': 'ಸಮಸ್ಯೆ ವರದಿ',
  'citizen.tab.chat': 'ಚಾಟ್',
  'citizen.tab.profile': 'ಪ್ರೊಫೈಲ್',
  'citizen.report.title': 'ಹೊಸ ಸಮಸ್ಯೆಯನ್ನು ವರದಿ ಮಾಡಿ',
  'citizen.report.category': 'ವರ್ಗ',
  'citizen.report.description': 'ವಿವರಣೆ',
  'citizen.report.state': 'ರಾಜ್ಯ',
  'citizen.report.city': 'ನಗರ',
  'citizen.report.submit': 'ಸಮಸ್ಯೆ ಸಲ್ಲಿಸಿ',
  'citizen.chat.support': 'CIVICSETU ಸಹಾಯ',
  'citizen.chat.placeholder': 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
  'citizen.profile.title': 'ನನ್ನ ಪ್ರೊಫೈಲ್',
  'citizen.summary.title': 'ಸಮಸ್ಯೆಗಳ ಸಾರಾಂಶ',
  'citizen.donate': 'ಎನ್‌ಜಿಒಗೆ ದೇಣಿಗೆ ನೀಡಿ',
  'authority.title': 'ಅಧಿಕಾರಿ ಪೋರ್ಟಲ್',
  'authority.tab.dashboard': 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
  'authority.tab.issues': 'ಎಲ್ಲಾ ಸಮಸ್ಯೆಗಳು',
  'authority.tab.bidding': 'ಕಾಂಟ್ರಾಕ್ಟರ್ ಬಿಡ್‌ಗಳು',
  'authority.tab.ngo': 'ಎನ್‌ಜಿಒ ವಿನಂತಿಗಳು',
  'contractor.title': 'ಕಾಂಟ್ರಾಕ್ಟರ್ ಪೋರ್ಟಲ್',
  'contractor.tab.bids': 'ತೆರೆದ ಬಿಡ್‌ಗಳು',
  'contractor.tab.projects': 'ನನ್ನ ಪ್ರಾಜೆಕ್ಟ್‌ಗಳು',
  'contractor.tab.profile': 'ಪ್ರೊಫೈಲ್',
  'ngo.title': 'ಎನ್‌ಜಿಒ ಪೋರ್ಟಲ್',
  'ngo.tab.issues': 'ಪರಿಹಾರವಾಗದ ಸಮಸ್ಯೆಗಳು',
  'ngo.tab.requests': 'ನನ್ನ ವಿನಂತಿಗಳು',
  'ngo.tab.analytics': 'ವಿಶ್ಲೇಷಣೆ',
  'ngo.tab.donations': 'ದೇಣಿಗೆಗಳು',
};

const translationOverrides: Record<Language, Partial<Translations>> = {
  en: {},
  hi: hiTranslations,
  ta: taTranslations,
  mr: mrTranslations,
  kn: knTranslations,
};

const isLanguage = (value: string | null): value is Language =>
  LANGUAGE_OPTIONS.some(option => option.code === value);

const interpolate = (template: string, params?: TranslationParams) => {
  if (!params) return template;

  return template.replace(/\{(\w+)\}/g, (_, key) => {
    const value = params[key];
    return value === undefined ? `{${key}}` : String(value);
  });
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: TranslationParams) => string;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    const storedLanguage = window.localStorage.getItem(STORAGE_KEY);
    return isLanguage(storedLanguage) ? storedLanguage : 'en';
  });

  const dictionary = useMemo(
    () => ({ ...baseTranslations, ...translationOverrides[language] }),
    [language],
  );

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(STORAGE_KEY, lang);
    }
  }, []);

  const t = useCallback(
    (key: string, params?: TranslationParams) => {
      const template = dictionary[key] || baseTranslations[key] || key;
      return interpolate(template, params);
    },
    [dictionary],
  );

  useEffect(() => {
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language;
    }
  }, [language]);

  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLang must be used within LanguageProvider');
  return ctx;
}
